### ISSUE TITLE
Pagination Issue Through Webpack

### ISSUE THREAD

**Issue by NtsikaMngoma** [jhipster/jhipster-dotnetcore#378] opened 2020-09-22 05:57 UTC
For some reason, as soon as I add in the api url into webpack.common.js, the pagination goes away but when I am running in development it shows.
new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: `'${options.env}'`,
                BUILD_TIMESTAMP: `'${new Date().getTime()}'`,
                VERSION: `'${packageJson.version}'`,
                DEBUG_INFO_ENABLED: options.env === 'development',
                // --API Url
                SERVER_API_URL: `''`
            }
        }),
![users](https://user-images.githubusercontent.com/40614110/93848226-45445480-fca9-11ea-8f82-a61a568acc4c.PNG)

**Comment by NtsikaMngoma** [comment] 2020-09-22 06:58
![pagination](https://user-images.githubusercontent.com/40614110/93852082-aa03ad00-fcb1-11ea-9258-f48434e4e954.PNG)
This is the application when I have the SERVER_API_URL CONST empty.

**Comment by nicolas63** [comment] 2020-09-22 19:49
Why you have set this variable ?

**Comment by NtsikaMngoma** [comment] 2020-09-22 20:49
Because it seems like when I build using npm run build webpack:prod, it requires the address to be there. In my case it's http://localhost:5000

**Comment by nicolas63** [comment] 2020-09-22 21:10
you served front in a different host ? Today it's the server who served angular with kestrel so the client is also on http://localhost:5000 and the variable SERVER_API_URL useless because it's relative to the server. 
You can separate the front and the back but you need to remove the angular spa on the server

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:14
Then what causes the pagination issue irrespective of the application structure? I did try deploying the jhipster demo project and I get the same pagination issue. That's what I am trying to understand.

**Comment by nicolas63** [comment] 2020-09-22 21:23
With this variable empty you have the same issue ? If yes can you analyze network ?

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:27
When it's empty it's not a problem but as soon as I  add in the api url then it creates the issue, mainly being that as far as I have read the project, when I build the static files, there must be the server url In  webpack.common.js when I have to deploy. Is that correct?

**Comment by nicolas63** [comment] 2020-09-22 21:37
No you don't need to set it. Because the dotnet server serve the application with kestrel and if the variable is empty the adress is relative to the server here localhost:5000

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:38
Okay, I see. Then what if the applications are deployed separately?

**Comment by nicolas63** [comment] 2020-09-22 21:43
If the application is deployed separatly you need to refactor/remove the server (SPA) and set this variable.

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:45
I will try again but last time I deployed the monolith application, I still had the pagination issue only when running prod profile after webpack:prod build.

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:46
But when I run npm with dev profile it's fine.

**Comment by NtsikaMngoma** [comment] 2020-09-28 07:50
I still haven't found a resolution for this bug as it's also happening to with your demo projects every-time I compile the project for production. Have you any idea? Also, what are the passwords for the seeded users in IdentityStartup from admin to anonymous?

**Comment by nicolas63** [comment] 2020-09-28 09:05
I think your deployment is not good. With the SPA like the examples it's kestrel that serves the front. Just run donet publish and dotnet YourAppName.dll. If you want separate front and back you need to change SPA in the backend

**Comment by NtsikaMngoma** [comment] 2020-09-28 09:07
> 
> 
> I think your deployment is not good. With the SPA like the examples it's kestrel that serves the front. Just run donet publish and dotnet YourAppName.dll. If you want separate front and back you need to change SPA in the backend

I have both applications separated, so please advise in step required.

**Comment by NtsikaMngoma** [comment] 2020-09-28 09:08
Although that's the case, the demo jhipster project encounters the same issue, of which is why I am confused.

**Comment by nicolas63** [comment] 2020-09-28 09:10
for the user : the mdp is the same than ident

**Comment by nicolas63** [comment] 2020-09-28 09:25
> 
> 
> Although that's the case, the demo jhipster project encounters the same issue, of which is why I am confused.

Witth the sample project if you use run dotnet publish and dotnet run App.dll you have the same issue ? 
If you have separated application you need to remove AddSpa and UseSpa in MvcStartup.cs. You also need to verify CORS and finally you can set SERVER_API_URL in webpack

**Comment by NtsikaMngoma** [comment] 2020-09-28 09:29
> 
> 
> > Although that's the case, the demo jhipster project encounters the same issue, of which is why I am confused.
> 
> Witth the sample project if you use run dotnet publish and dotnet run App.dll you have the same issue ?
> If you have separated application you need to remove AddSpa and UseSpa in MvcStartup.cs. You also need to verify CORS and finally you can set SERVER_API_URL in webpack

Yes, I get the same issue.

**Comment by NtsikaMngoma** [comment] 2020-09-28 09:30
As soon as I assign an API uri to the SERVER_API_URL, the pagination changes even in dev mode.

**Comment by nicolas63** [comment] 2020-09-28 09:32
Can you create a git repo with your code and describe all steps to reproduce ?

**Comment by NtsikaMngoma** [comment] 2020-09-28 10:41
I see the issue only happens when I break up the monolith between server and client applications, if this is the case, what are the steps I am required to follow?

**Comment by NtsikaMngoma** [comment] 2020-09-28 11:30
Is this not based on response headers from CORS? I am reading the response and they are not the same.

**Comment by NtsikaMngoma** [comment] 2020-09-28 11:35
This is for the production profile: HTTP/1.1 200 OK
Content-Length: 6188
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
X-Total-Count: 4
X-Pagination: {"totalCount":4,"size":20,"page":0,"totalPages":0,"isFirst":true,"isLast":true,"hasNext":false,"hasPrevious":false}
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: "Authorization,Link,X-Total-Count"
X-Powered-By: ASP.NET
Date: Mon, 28 Sep 2020 11:27:50 GMT

and this is the dev profile: HTTP/1.1 200 OK
x-powered-by: Express
connection: close
date: Mon, 28 Sep 2020 11:34:41 GMT
content-type: application/json; charset=utf-8
server: Kestrel
content-length: 7573
x-total-count: 9
x-pagination: {"totalCount":9,"size":20,"page":0,"totalPages":0,"isFirst":true,"isLast":true,"hasNext":false,"hasPrevious":false}

**Comment by nicolas63** [comment] 2020-09-28 11:39
For me the production response is good, have you any error on client console ?

**Comment by NtsikaMngoma** [comment] 2020-09-28 11:42
> 
> 
> For me the production response is good, have you any error on client console ?

No, there are no errors.

**Comment by nicolas63** [comment] 2020-09-28 11:56
i reproduce the error (with dev and prod profile) i will investigate, can you verify if the java version have the same problem ? If not can you compare the request/response ?

**Comment by nicolas63** [comment] 2020-09-28 12:00
this line `protected onSuccess(data: IMyEntity[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));`

return 0

**Comment by nicolas63** [comment] 2020-09-28 12:09
Maybe a problem with our CORS configuration (appsettings.json)

**Comment by NtsikaMngoma** [comment] 2020-09-28 14:00
**"Cors": {
      "AllowedOrigins": "http://server.local",
      "AllowedMethods": "*",
      "AllowedHeaders": "*",
      "ExposedHeaders": "Authorization,Link,X-Total-Count,X-Pagination",
      "AllowCredentials": true,
      "MaxAge": 1800
    }**

> 
> 
> Maybe a problem with our CORS configuration (appsettings.json)

**Comment by nicolas63** [comment] 2020-09-28 15:01
it works with this ?

**Comment by maznag** [comment] 2020-11-14 14:40
* I can reproduce the bug when I run the frontend without TLS => redirection is made in the back to https:

`npm run start`

The X-Total-Count is present in the response returned by the BACK. On the other hand the `HttpHeaders` in the front only contains two parameters `content-length` and `content-type` and no `X-Total-Count`

* When I run the front with TLS => no problem

`npm run start-tls`

@NtsikaMngoma to separate frond and backend you can use `skip-server` and `skip-client` options

- use main generator JHIPSTER to generate frontend as follow:

`jhipster --skip-server --db=sql --auth=jwt`

- use dotnet blueprint to generate backend as follow:

`jhipster --blueprints dotnetcore --skip-client`

with `--skip-client` option the SPA config is not generated and no need to remove `AddSpa` and `UseSpa`.

@NtsikaMngoma @nicolas63 can you check if it works when using TSL on the frontend ?

Don't forget to check CORS config:

    ```
"Cors": {
      "AllowedOrigins": "*",
      "AllowedMethods": "*",
      "AllowedHeaders": "*",
      "ExposedHeaders": "Authorization,Link,X-Total-Count,X-Pagination",
      "AllowCredentials": true,
      "MaxAge": 1800
    }
```

**Comment by nicolas63** [comment] 2020-11-17 13:11
@maznag do you think redirection is the problem ?

**Comment by maznag** [comment] 2020-11-17 14:28
yes, redirection is the problem when we start Front without TLS. it works well when we start Front with TLS and call Backend directly with https.

can you check with and without TLS to confirm ? and don't forget to use separate frontend and backend.

thanks for feedback :-)

**Comment by nicolas63** [comment] 2020-12-13 21:05
@maznag i have test this and i have the problem only only without tls but i have no idea how to solve the problem.
Do you have an idea ?

**Comment by maznag** [comment] 2020-12-14 20:50
@nicolas63 thanks for the confirmation. 

To solve this issue we need to not force HTS by default on the back and use `UseHttps` in appSettings.Env.json to specify if user want to use TLS or not. Otherwise, Backend can be accessible in http protocol by default (`UseHttps: false`). 

When we use Front with TLS, we should use `UseHttps: true`

We can also aadd the new settings parameters as follow to load certificate file and/or password for others environments (preprod, prod).

```
"UseHttps:" true,
"ServerCertificate": {
      "SigningCertificateFile": "Resources/localhost_public_privatekey.pfx",
      "SigningCertificatePassword": "***************"
 }
```

I can propose a PR if you agree.

**Comment by nicolas63** [comment] 2020-12-14 21:59
@maznag first sorry for the delay of my last response

And yes ! Your response is really a good idea.

If you can do a PR it would be perfect.
Tanks

**Comment by maznag** [comment] 2021-01-05 22:04
Closed via https://github.com/jhipster/jhipster-dotnetcore/pull/514

**Closed** 2021-01-05 22:03 UTC
Labels: bug 🐞
