### ISSUE TITLE
Date Issue on client application

### ISSUE THREAD

**Issue by mark-mngoma** [jhipster/jhipster-dotnetcore#373] opened 2020-09-18 09:41 UTC
I have been testing the sample dotnet project and notice that the client app has an issue is saving dates previous to the one inputted on the form but it works well with postman. Is the issue in this line of code: **if (!employee.id) {
        const today = moment().startOf('day');
        employee.hireDate = today;
      }**
in the employee-update component?

**Comment by NtsikaMngoma** [comment] 2020-09-18 09:43
I chose 2020-09-18 but api response payload gives 2020-09-17

**Comment by nicolas63** [comment] 2020-09-18 10:27
Our clients code is based on java version can you verify if the java application has the same bug ?

**Comment by NtsikaMngoma** [comment] 2020-09-18 10:41
I have a java project running and it is fine, but I think the problem is within the dotnet client application neither java or dotnet server applications.

**Comment by nicolas63** [comment] 2020-09-18 11:41
The dotnet client (angular) is exactly the same than java version. Which version of jhipster is on your java project?

**Comment by NtsikaMngoma** [comment] 2020-09-18 12:45
They are not exactly. I am actually testing this project: https://github.com/jhipster/jhipster-sample-app-dotnetcore

**Comment by NtsikaMngoma** [comment] 2020-09-18 12:46
The java project is running version 5.4.2, which is working fine.

**Comment by nicolas63** [comment] 2020-09-18 12:49
This blueprint is base on jhipster 6.10.1

**Comment by NtsikaMngoma** [comment] 2020-09-18 12:53
Yes it is, but the bug persists on this version as well as I am testing on the latest and it seems the date reverts a day back.

**Comment by nicolas63** [comment] 2020-09-18 13:34
Ok if think is link to https://github.com/jhipster/generator-jhipster/issues/11740

**Comment by NtsikaMngoma** [comment] 2020-09-18 13:39
This issue is not happening on the Java project, only the dotnet project.

**Comment by nicolas63** [comment] 2020-09-18 14:09
Ok i will investigate this problem

**Comment by NtsikaMngoma** [comment] 2020-09-22 05:55
Still an issue I am failing to resolve as I don't know whether the issue is how the date is parsed on the client application, because when I test on postman, everything works fine, so the issue is the client.

**Comment by nicolas63** [comment] 2020-09-22 19:48
Can you give me more information i can't reproduce this on my machine, can you give me jdl / jhipster version / your machine os ?

**Comment by NtsikaMngoma** [comment] 2020-09-22 20:46
It's this repo:https://github.com/jhipster/jhipster-sample-app-dotnetcore that I am running on the latest version of Windows 10 and also on docker.

**Comment by nicolas63** [comment] 2020-09-22 21:12
you don't generate an application ? you use directly the sample ? ok can try to reproduce with the sample

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:15
Yes, I am using the sample project to reference the logic on the client application, especially when it comes to setting datepickers through moment.js as you're using it in the sample project.

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:16
I have a generated project, which I am referencing from the sample project.

**Comment by nicolas63** [comment] 2020-09-22 21:31
Everything in the example is generated with the generator.  But ok I will try again to reproduce.

Thanks for your feedback.

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:35
Sure, please just working in doing a form post on the client to see the issue as it doesn't occur when testing with swagger or postman.

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:35
Any field with datetime

**Comment by nicolas63** [comment] 2020-09-22 21:40
I have try this but it's ok for me. Wich date format is on your os ?

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:43
Really? Does it not set to the date before? Like if you select 2020-06-04 then it persists as 2020-06-03?

My os datetime format is ddmmyyyy.

**Comment by nicolas63** [comment] 2020-09-22 21:47
I have the same format. Can you try to generate an application with the latest version on the master ? ( you need to clone and call `npm link` )

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:49
Using the jhipster generator and the jdl for entities or the demo repo?

**Comment by nicolas63** [comment] 2020-09-22 21:51
Generator and jdl or you can also use entity cli

**Comment by nicolas63** [comment] 2020-09-22 21:53
`git clone`
`cd repo`
`npm link`
`jhipster --blueprints dotnetcore`
`jhipster entity YourEntity`

**Comment by NtsikaMngoma** [comment] 2020-09-22 21:58
I am still getting the same issue, I am testing with entity employee, field hireDate

**Comment by NtsikaMngoma** [comment] 2020-09-23 07:28
I did everything here but I am still getting this issue. Please send me a screenshot of the process.

**Comment by NtsikaMngoma** [comment] 2020-09-23 08:53
I am still receiving this issue on response payload it shows date as **hireDate: 2020-09-22T22:00:00**, but date chosen was: 2020-09-23T22:00:00

**Comment by NtsikaMngoma** [comment] 2020-09-23 10:23
I am debugging and the timestamp is just being set at 22h00, I am not sure what config is handling this but it's on the client application, not the api.

**Comment by NtsikaMngoma** [comment] 2020-09-23 11:29
It seems like this bug is some UTC parsing issue with Moment as it's happening with all the client applications from the dotnetcore generator.

**Comment by nicolas63** [comment] 2020-09-23 11:45
sorry for the delay, yes it's possible that the error comes from moment.js and UTC

**Comment by NtsikaMngoma** [comment] 2020-09-23 11:48
I am thoroughly reading the moment documentation but if you have an idea on fixing the bug please give me an update when possible.

**Comment by nicolas63** [comment] 2020-09-23 11:48
in which timezone are you ?

**Comment by NtsikaMngoma** [comment] 2020-09-23 11:51
SAST UTC+2

**Comment by nicolas63** [comment] 2020-09-23 12:10
Can you try to add ` options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;`
in newtonsoft options in MvcStartup.cs ?

**Comment by NtsikaMngoma** [comment] 2020-09-23 13:10
I have added. Issue still persists as is

**Comment by NtsikaMngoma** [comment] 2020-09-23 14:35
I am testing the Java project and it's doing the same thing. Any ideas of configuring moment() properly?
![Screenshot (137)](https://user-images.githubusercontent.com/40614110/94027042-b9bae880-fdba-11ea-8c88-6bca7581b00f.png)

**Comment by NtsikaMngoma** [comment] 2020-09-23 14:37
It's a weird issue, very difficult to debug where it's coming from.

**Comment by NtsikaMngoma** [comment] 2020-09-23 14:38
But it is definitely an issue on client application parsing the date properly.

**Comment by nicolas63** [comment] 2020-09-23 14:57
if the bug il also on the java version can you open an issue on https://github.com/jhipster/generator-jhipster ?

check before if the issue is not already open

**Comment by NtsikaMngoma** [comment] 2020-09-28 07:58
I managed to get this fixed but it would be great for you to look at it and fix it for future releases.

**Comment by nicolas63** [comment] 2020-09-28 08:02
@NtsikaMngoma how did you fix it ?

**Comment by NtsikaMngoma** [comment] 2020-09-28 08:07
> 
> 
> @NtsikaMngoma how did you fix it ?
https://github.com/jhipster/generator-jhipster/issues/12577

**Comment by nicolas63** [comment] 2020-09-28 08:36
Ok but we need to take open this issue while the other issue is not resolve

**Comment by NtsikaMngoma** [comment] 2020-09-28 08:42
It's the same issue, should I close it or will you close it once resolved?

**Comment by NtsikaMngoma** [comment] 2020-09-28 08:42
Please have a look at this issue as I am battling to figure it out: https://github.com/jhipster/jhipster-dotnetcore/issues/378

**Closed** 2022-09-26 19:50 UTC
Labels: bug 🐞
