### ISSUE TITLE
generator-jhipster-dotnetcore@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by asdini** [jhipster/jhipster-dotnetcore#31] opened 2019-08-12 16:08 UTC
Hi,

I am following the instruction on the ReadMe page, but I try to install the dotnetcore generator, I get the error blow.  If it is not available in npm registry, can I clone the project and link it as you would do for Development.

 npm install -g generator-jhipster-dotnetcore
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/generator-jhipster-dotnetcore - 
Not found
npm ERR! 404 
npm ERR! 404  'generator-jhipster-dotnetcore@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahmeddini/.npm/_logs/2019-08-12T15_42_53_460Z-debug.log

**Comment by danielpetisme** [comment] 2019-08-12 17:04
Hello,

Thanks for reporting the issue. Indeed, the dotnet blueprint is not yet in npm registry. The README instructions have been generated when I started the blueprint but they are not usable yet, sorry for that. I really need to update the instructions until a public release.

If you want to try the blueprint.
```
git clone https://github.com/jhipster/jhipster-dotnetcore.git
cd jhipster-dotnetcore
npm link
mkdir /tmp/myApp
cd /tmp/myApp
npm link generator-jhipster-dotnetcore
jhipster -d --blueprint dotnetcore
```
Normally, after the the application type and application name questions, you should have .Net questions (the default namespace).

Feel free to comment the issue if you need more help.

**Comment by asdini** [comment] 2019-08-12 19:12
Hi Daniel,

Thanks for the prompt reply. As a side note, I normally develop JHipster with Java, but my colleagues are very experienced .NET developers. They were very exited about JHipster but sadly before your blueprint, it wasn't supported.  I need to introduce them to this blueprint so that they can develop with it and even contribute to it. It looks like you started the project recently but we can help.

Back to the issue,  I understand the blueprint is not available on npm registry yet. I tried to follow your instructions, cloned the project, npm linked it.  created a new new directory, linked npm linked it to the generator-jhipster-dotnetcore.  then I run the blueprint command.

Instead of generating a .Net app, it is generating a Java and Angular client. 
See the screenshot below please. 
<img width="1192" alt="Screen Shot 2019-08-12 at 23 02 17" src="https://user-images.githubusercontent.com/14091236/62891351-88b65a80-bd56-11e9-8425-62be07019f04.png">

**Comment by asdini** [comment] 2019-08-12 19:29
If it helps, below are the versions of Node, npm, jhipster and yo installed my Mac laptop.
<img width="353" alt="Screen Shot 2019-08-12 at 23 27 57" src="https://user-images.githubusercontent.com/14091236/62892283-f794b300-bd58-11e9-9e83-22ececfb0361.png">

**Comment by danielpetisme** [comment] 2019-08-12 21:21
Thanks for the details!

Many people is reporting issues to generate a .Net app but we have troubles
to reproduce it.

I'll investigate, I may come back to you for further details.

**Comment by asdini** [comment] 2019-08-13 01:10
I have read their comments too, the thing they have in common is they used MAC laptop.  Please test it on MacOS

**Comment by danielpetisme** [comment] 2019-08-13 08:21
I do have a Mac and it works....

Can you give me the HEAD commit to be sure we're using the same version.
Thanks

Le mar. 13 août 2019 à 03:10, Ahmed Dini <notifications@github.com> a
écrit :

**Comment by asdini** [comment] 2019-08-13 08:33
Thanks Daniel for investigating the issue.  If there is any thing, I can do to help, including giving you remove access, if you can't reproduce, I will be glad to help.

Below is the Head Commit info,

commit b36a1b72553663ddab5fc22a2beb98b01b7f1367 (HEAD -> master, origin/master, origin/HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Thu Aug 1 21:18:06 2019 +0200
    Bump lodash from 4.17.10 to 4.17.13 (#18)
    Bumps [lodash](https://github.com/lodash/lodash) from 4.17.10 to 4.17.13.
    - [Release notes](https://github.com/lodash/lodash/releases)
    - [Commits](https://github.com/lodash/lodash/compare/4.17.10...4.17.13)
    Signed-off-by: dependabot[bot] <support@github.com>

**Comment by asdini** [comment] 2019-08-13 10:45
Hi Daniel, thanks for the support,
It works now! It requires .Net Core to be installed on the system, I had it installed but forgot to set the path to the installation as PATH variable. I have noticed you have a dotnet.js file under generators that checks for if dotnet is installed but it doesn't work properly. 
For anyone with the same issue this is how I fixed (MAC)
1. Follow the instructions above by Daniel
2. Install .Net from this link https://dotnet.microsoft.com/download/dotnet-core (select the current version, currently the current version is 2.2)
3. Go to the next Download page on the link above, under Build apps - SDK, download the .NET Core Installer: x64
4. Run the Installer and follow the instructions by the installer, remember the directory of installation as the installer will not set the Path, meaning you will not be able to run dotnet command on Terminal. I didn't change the default installation directory so it picked the default which is /usr/local/share/dotnet
5. To set the PATH entry, open .bash_profile file in your user home directory, with an editor, I use vi .bash_profile on terminal and add a new line
`   export PATH=/usr/local/share/dotnet:$PATH`
6.  Close the editor and save the changes, and on terminal run  source .bash_profile
7. Close the terminal and open a new terminal window and type dotnet to see if it picks up.

**Comment by danielpetisme** [comment] 2019-08-13 11:38
Awesome!!
I completely forgot this sanity check.
IMHO, the appropriate behavior would be to warn the user if the `dotnet`
command isn't in the PATH (just as jhipster does with `java` or `npm`).
WDYT?
Do you want to propose a PR for that?
Again thank you for spotting the issue.

Le mar. 13 août 2019 à 12:45, Ahmed Dini <notifications@github.com> a
écrit :

**Comment by asdini** [comment] 2019-08-13 12:09
Thanks, Yes, you right, we need to do some Minimal System Requirement checks, including checking if .Net is installed.  I am exploring the system, but definitely will create a PR for this .Net Requirement issue.   To attract contributors to the project, we need to have proper documentation.
1. Contributor documentation, I rarely see, opensource projects that have, these as they expect contributors to be familiar with the technologies the project is based on (such as to be a contributor, you need to be familiar with Yo (Yeoman)
2. Also we need documentation of the Consumer/developer  of the project to generate his/her own .Net Backend and (React, Angular, Vue) frontend.  

I will personally contribute to the project, as I am working closely with .Net developer who can advance this project, but what do you suggestion?  To bring them onboard, that is why I said we need clear documentation of what steps they need to take to contribute the project and what tools they need to learn, links to the resources. etc.

**Comment by asdini** [comment] 2019-08-20 16:17
Hi Daniel,

Thanks for the fix. I have tested.  I can confirm the dotnet issue has been fixed. But you have introduced another bug which causes the build to fail when I run this command in the root directory of the .Net and Angular project generated by the blueprint. 
dotnet run --verbosity normal --project ./src/DebugVsCodeFolder/DebugVsCodeFolder.csproj

This is caused by importing the rtl.scss file which has a wrong import path in the vendor.scss file. See the attached screenshot. 
I temporarily fixed the path for my generated app by replacing it the import with the line below in the vendor.scss file:-
@import './rtl.scss';

No the project builds and runs in the command line. It works perfectly.

However, I tried to open the project build and run using Visual Studio(Community version 8) not Visual Studio Code.
But it doesn't run, somehow, Visual Studio can't resolve the dependency Library JHipsterNet
and get this error.

/Users/ahmeddini/Library/Caches/VisualStudio/8.0/MSBuild/72488_1/Microsoft.CSharp.CurrentVersion.targets(5,5): Error MSB4019: The imported project "/Users/ahmeddini/Library/Caches/VisualStudio/8.0/MSBuild/72488_1//Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019) (JHipsterNet)

I think this could be solved easily by experienced .Net developer as I am a Java developer and my .Net knowledge is limited. 

I have also been trying to run the project on fresh Windows computer and now preparing instructions for beginners to run the dotnet generator.  The fact that the blueprint is not available on npm respository makes matters difficult to run the project as we have to link few times.
So far I prepared a draft instructions to run the project see below:-
Also I am preparing myself and my colleagues to contribute the project, we have been experimenting debugging the jhipster-dotnetcore blueprint with Visual Studio Code, following this tutorial prepared by Anthony Viard
 https://medium.com/jhipster/how-to-debug-jhipster-blueprints-with-vscode-d596d6be0707
I have managed to make it work like the parent JHipster generator, it requires the inclusion of the .vscode directory and tasks.json and launcher.json file inside the .vscode directory, I have attached the file as vscode.zip, you can extract it and add it to the the root directory of the jhipster-dotnetcore if you are happy with it, in the future I will submit a Pull Request. 

nstructions for .Net Jhipster app generation on windows

1. Download Node and npm from here https://nodejs.org/en/ and install it.
2. Open Command Prompt via cmd
3. type npm --version (you should get the version name)
4. Type node --version (note Node has been installed but currently we only need npm)
5. On Command prompt Install yeoman (yo) via npm.... npm install -g yo
6. Now install Jhipster using the command below on command prompt.
npm install -g generator-jhipster
7. Since the .NET Jhipster generator is not published yet to npm repository, we have to install it locally and link it.
8. Download and Install git if it is not already on your system - https://git-scm.com/download/win
9. After git is installed, open command prompt and run the command below in a directory you are happy with.
git clone https://github.com/jhipster/jhipster-dotnetcore.git
10. cd jhipster-dotnetcore
11. Run the command below to make this generator available globally
npm link
12. Do 'cd ..' to get out of the jhipster-donetcore directory
13. Download and install .NET Core 2.2 on computer and make the 'dotnet' command available on command prompt (set in path)
https://dotnet.microsoft.com/download
14. We need to generate a .Net Core 2.2 application with Angular frontend so create a folder for it
mkdir dotnetAngularApp
15. cd dotnetAngularApp 
16. Now link the new app folder that we generated now with global npm of the generator
npm link generator-jhipster-dotnetcore
17. Run the command below to start the generation of the .NET and Angular application as one app
jhipster -d --blueprint dotnetcore
18. The command prompt will start showing question prompts. 
a. Which Type of application would you like to create?
Monolithic application
b. What is the base name of your application?
dotnetAngularApp
c. What is your default C# namespace? <MyCompany> Timeline
d. Would you like to enable internationalization support? <Y/n>, choose Y 
e. Please choose the native language of the application <Use Arrow Keys>, Select English and hit enter key
f. Please choose additional languages to install <Press <space key> to select? Arabic <Libya>
g. Besides Junit and Jest, which testing frameworks would you like to use? NONE, just press enter key
h. Would you like to install other generators from from JHipster market? press N

19. The .Net application and its Angular frontend will be generated for you.
20. from the dotnetAngularApp directory run the commands blow:-
cd \src\DotnetAngularApp
npm link generator-jhipster-dotnetcore
npm install
21. Run the command below on command prompt to run the generator .Net and Angular application in the DotnetAngularApp root folder of the generated app.
dotnet run --verbosity normal --project ./src/DebugVsCodeFolder/DebugVsCodeFolder.csproj

22. go to http://localhost:5001 and login with username admin, password admin

23. Download Vistual Studio and open the projec with it to see the magic code



[vscode.zip](https://github.com/jhipster/jhipster-dotnetcore/files/3521583/vscode.zip)







<img width="1440" alt="Screen Shot 2019-08-20 at 19 54 59" src="https://user-images.githubusercontent.com/14091236/63363360-81a9d080-c384-11e9-913f-a991144d8509.png">


<img width="689" alt="Screen Shot 2019-08-20 at 19 40 06" src="https://user-images.githubusercontent.com/14091236/63362871-93d73f00-c383-11e9-82c9-46a055d7446f.png">

**Comment by danielpetisme** [comment] 2019-08-20 18:55
Salaam Ahmed!

You're good to spot issues and their fix, thanks! 
The good news is that I fixed it on the master https://github.com/jhipster/jhipster-dotnetcore/commit/43c320e481cd80a98194b293fc574514bbe336c8 you can test it.

I plan to publish an alpha version of the blueprint this week. Actually I wanted to do it today but I had to unpublish it and npm registry forces me to wait 24H... that's good I could fix plenty issues. The only remaining task I have is to generate a decent `README.md` to help to run `npm install`, `dotnet run` and `docker build` on the generated application. So we are really really close!

It's really awesome that you plan to show the blueprint to your .Net devs, I'm really looking forward hearing your feedback, it will useful insights for the project. Thank you!

Regarding the Visual Studio project import... I gave up with the Mac version because it was 💩 The .Net solution and project organisation is weird for me too (I'm a Java dev actually) but I succeed to load everything into VS Code or IntelliJ Rider.

Your **Getting started with JHipster .Net** is cool. I don't know if you maintain a blog but it could be a great post I (and the JHipster community) could share.

Finally, to ease the issue management, could we only discuss one problem per ticket, please. We start with the lack of the generator to the registry, we moved to the `dotnet` command issue and finally the rtl problem. Clear seprated issue is issue to build a knowledge base rather than digging into a long thread).
In advance thanks.

I think we cover all the point. If the RTL works, please close the issue.
Again thank you for your help

**Comment by danielpetisme** [comment] 2019-11-04 22:53
Solved with the release
https://www.npmjs.com/package/generator-jhipster-dotnetcore

**Closed by danielpetisme** 2019-11-04 22:53 UTC
